### ISSUE TITLE
Repeater property in flexible property

### ISSUE THREAD

**Issue by danfri86** [wp-papi/papi#102]
I'm using version 2.3.5 and am unable to use the repeater property as part of the flexible property. It doesn't output any fields or buttons for my repeater. This is what I've tried:

    $this->box( 'My box', [
        papi_property( [
            'title'    => 'Flexible content',
            'slug'     => 'my_flexible_slug',
            'type'     => 'flexible',
            'settings' => [
                'items' => [
                    [
                        'title' => 'Images',
                        'items' => [
                            papi_property( [
                                'title' => 'Image',
                                'slug'  => 'my_image_slug',
                                'type'  => 'image'
                            ] )
                        ]
                    ]
                ]
            ]
        ])
    ]);

**Comment by frozzare** [comment]
I have tested the code you provided and it works great for me. I can add new images when I click `Add new row`.

Do you get any JavaScript errors?

**Comment by danfri86** [comment]
I'm so sorry, I wrote my code wrong and of course forgot the repeater field. This is my actual code:

```php
$this->box( 'My box', [
  papi_property( [
    'title'    => 'Flexible content',
    'slug'     => 'my_flexible_slug',
    'type'     => 'flexible',
    'settings' => [
      'items' => [
        [
          'title' => 'Images',
          'items' => [
            papi_property( [
              'title'    => 'Repeater',
              'slug'     => 'my_repeater_slug',
              'type'     => 'repeater',
              'settings' => [
                'items' => [
                  papi_property( [
                    'title' => 'Image',
                    'slug'  => 'my_image_slug',
                    'type'  => 'image'
                  ] )
                ]
              ]
            ] )
          ]
        ]
      ]
    ]
  ])
]);
```

**Comment by frozzare** [comment]
Yep, you're right about that the repeater property don't render in a flexible. Papi don't allow it and that will not be changed.
