### ISSUE TITLE
Prefix classes appended by `papi_body_class()`

### ISSUE THREAD

**Issue by entr** [wp-papi/papi#104]
WP is prefixing all dynamic body classes (page-id-865 page-template page-template-qa) and papi should too. I think `papi-type-nicetypeslug` should be enough since WP is providing classes for everything else.

Having only the type slug as body class did conflict with my CSS rule set otherwise I wouldn't ever notice it.

**Comment by frozzare** [comment]
Well, yes this is a good idea but a bad idea to implement now when people build sites with the existing classes. I think `about-page-type` is enough for now.
