### ISSUE TITLE
Property link - Removed link are not recorded

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#109]
Link properties are not recorded when deleted. 

Test case: 
- add a link
- save/update
- remove the link
- update

Link is still here.

**Comment by frozzare** [comment]
Yes, that's true. But Papi do not keep a list of fields that exists so when deleting a link property the property do not now which fields to trash. So the link property can't solve this, it's a general property issue (repeater and flexible has trash functionality).

Keeping a list with all properties that exists when you run update should be a solution.

**Comment by frozzare** [comment]
Can you verify the fix in `dev-master`?

**Comment by nlemoine** [comment]
I'll check it tomorrow morning. Thanks for the quick fix!

**Comment by nlemoine** [comment]
Just tested `dev-master`, it looks good to me. Thanks!

**Comment by frozzare** [comment]
Great! Will release a patch version of 2.4 later today or tomorrow.

**Comment by frozzare** [comment]
https://github.com/wp-papi/papi/releases/tag/v2.4.4
