### ISSUE TITLE
Option - Save process

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#113]
Hi @frozzare, 

I noticed an issue when saving option with the link property. It's actually not the property itself but the fact that you're using the `url_to_postid` method in the `update_value` method of that property. 

Saving the link property will result in a fatal error: 
```
Fatal error: Call to a member function wp_rewrite_rules() on null in wp-includes/rewrite.php on line 434
```

The `url_to_postid` uses the global object `$wp_rewrite` that's not already set yet. That's because the `Papi_Admin_Option_Handler` class is instantiated too early in the WordPress process (on `plugins_loaded` as far as I can see) and should probably wait for a later hook. See 14 and 18 here: http://theme.fm/2011/09/wordpress-internals-how-wordpress-boots-up-part-2-2437/

I quickly fixed it with the code below but you'll probably handle it in a much cleaner way.
```php
add_action('admin_init', function() {
	if ( papi_is_method( 'post' ) && papi_is_option_page() ) {
		$this->save_options();
	}
});
```

**Comment by frozzare** [comment]
@nlemoine can you try `dev-master`? I have tested and the fix works, if it works for you I will release a small release with this fix.

**Comment by nlemoine** [comment]
Looks good to me too! 

I still have another issue related to the link property when used in option but I'll open a new ticket as it's not related to the saving process.
