### ISSUE TITLE
Link property option / retrieving value

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#115]
When using link property as an option, I can't get the value back in the template using `papi_get_option`. It returns an object with all values set to `false`. 

![capture d ecran 2015-11-08 a 13 55 47](https://cloud.githubusercontent.com/assets/2526939/11020479/753444fc-8620-11e5-8011-f07faea8aa73.png)

**Comment by frozzare** [comment]
Thanks for the issue. I will look over this and see if I can make some changes in 2.5, for 2.4.5 (will release it tomorrow) it's fixed with a easy fix :+1:

**Comment by nlemoine** [comment]
Thanks! :+1:

**Comment by frozzare** [comment]
https://github.com/wp-papi/papi/releases/tag/v2.4.5
