### ISSUE TITLE
[url property] clear input when save post

### ISSUE THREAD

**Issue by ekandreas** [wp-papi/papi#125]
Papi validates the property of type "url" and clears the input if not a valid URL address. Perhaps it should warn instead?
Here's an example of not valid url (don't know why, perhaps the ÅÄÖ):
http://www6.spsm.se/sok/?series=Spel+för+språkinlärning&utm_source=nyhetsbrev&utm_medium=email&utm_campaign=skolporten

**Comment by frozzare** [comment]
I can't reproduce this. This was how I tried to reproduce it:
1. Add url property to a page.
2. Add the url to the property and save.

When I used `papi_get_field` it did return http://www6.spsm.se/sok/?series=Spel+f%C3%B6r+spr%C3%A5kinl%C3%A4rning&utm_source=nyhetsbrev&utm_medium=email&utm_campaign=skolporten
