### ISSUE TITLE
papi property file saves no value to the post

### ISSUE THREAD

**Issue by ekandreas** [wp-papi/papi#129]
To reproduce the bug:

In the page type register function:
```php 
        $this->box( 'Missing data', [
            papi_property( 'properties/missing.php', [
                'slug' => 'missing_data',
                'title' => 'Write something here',
            ] ),
        ] );
```
The template file, properties/missing.php:
```php
<?php
return papi_property( [
    'description' => 'This is an example of template - missing data prop',
    'type'  => 'string',
    'slug'  => 'slug_to_overwrite',
]);
```

**Comment by ekandreas** [comment]
Edit the post and then open it again and the value disapears / empty.
Papi version master-dev and the version 2 branch gives the same effect.

**Comment by ekandreas** [comment]
If this is a bug, no high prio on this one :-)

**Comment by frozzare** [comment]
It's a bug with the slug when using a template like this.
