### ISSUE TITLE
Editor property default value

### ISSUE THREAD

**Issue by ekandreas** [wp-papi/papi#133]
How to set default value to property Editor?
Code example gives non html-value to the prop:
```php
            papi_property( [
                'slug' => 'profile_update_message',
                'title' => __('Profile Message','1ln'),
                'type' => 'editor',
                'default' => 'You need to update your profile, <a href="/profile/update">click here!</a>',
                'description' => 'Update Profile Message',
            ] ),
```

**Comment by rasmusbe** [comment]
The WordPress editor (and TinyMCE that WP uses) doesn't seem to have support for placeholders so I guess this requires use of extra plugins to the TinyMCE editor (like https://github.com/mohan999/tinymce-placeholder)

I don't know if this is a good idea, or if you should add an issue in the WordPress Bug Tracker to suggest WP to add placeholder support to the editor.

**Comment by frozzare** [comment]
But we could set the value to the default value if it don't exists in the database? I think that other properties works like that.

**Comment by rasmusbe** [comment]
Yes, but I think that can be bad for the user experience, since the editor seems empty until you have saved it.

**Comment by frozzare** [comment]
Yes that is a problem but I don't think that we like to modify how the wordpress editor works since it's a customized tinymce.

**Comment by rasmusbe** [comment]
I agree!

**Comment by ekandreas** [comment]
Ok, I will try to explain.
You can set the default value in the property of type Editor. When you do that the value shown to the user is non-html. It would be great if the value set to the Editor via the property control could be provided with content that is rendered as visual html.
You can regenerate the issue if you provide a default value to a Editor prop with eg a hyperlink and perhaps you understand what I want to address here :-)

**Comment by frozzare** [comment]
Ah, I see the problem now. Since the `default` value for Editor kind of works we should fix this issue.

The user experience is another problem that is harder to solve and maybe shouldn't be solve like it is right now, maybe with a button in the toolbar where you can click and then the default value is added to the editor.

**Comment by ekandreas** [comment]
I just think it's a decoding issue.

**Comment by frozzare** [comment]
https://github.com/wp-papi/papi/commit/6c4832e01b734c32d19e29baab1a4917f5627d55 will fix the issue and target for Papi 3.

**Comment by ekandreas** [comment]
Thanks!
