### ISSUE TITLE
[Utilities] - papi_nl2br

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#136]
There's an issue with the `papi_nl2br` method. Line breaks won't be replaced if surrounded by single quotes: http://php.net/manual/en/language.types.string.php#language.types.string.syntax.double

Even with the right quotes, I don't really see what is the purpose of this method? See test cases here: http://www.tehplayground.com/#zIdd7NRHU (hit CRTL + Enter to run code)
Getting double `<br />` on the output?

**Comment by frozzare** [comment]
We maybe can remove `papi_nl2br` and replace it with `nl2br`. I will test this and get back to you.

**Comment by frozzare** [comment]
Ah, the point with `papi_nl2br` is that it support single quotes, look at this example. http://www.tehplayground.com/#FRK9n4b1P

**Comment by frozzare** [comment]
```php
nl2br( str_replace( '\n', "\n", $str ) )
```

**Comment by nlemoine** [comment]
IMO, this is out of PHP scope and I really don't see in what cases the method could be useful.

That would be the same as trying to change PHP behavior to make it evaluate variables within single quotes.

**Comment by frozzare** [comment]
Well, I don't use double quotes when I do PHP and adding `\n` to a string is not a PHP feature, it's a Papi feature.

**Comment by nlemoine** [comment]
I don't use double quotes too. The need for manually adding line breaks in a string is extremely rare and when it happens, I use double quotes. I don't really see the use case, or at last don't agree with it but I see the purpose now ;)
