### ISSUE TITLE
Thumbnail click to add new page type

### ISSUE THREAD

**Issue by ekandreas** [wp-papi/papi#137]
It would be a better user experience if the user could click on the thumbnail/image for the page type to select when creating a new i wp-admin.

![thumbnail-click](https://cloud.githubusercontent.com/assets/1794603/12326084/de9e1e76-bace-11e5-8f96-5be824e62211.png)

**Comment by rasmusbe** [comment]
I agree, and I think the question is if only the image and the button should be linked or if the whole box should be a link. What do you think, @ekandreas and @frozzare ?

**Comment by frozzare** [comment]
Yeah, I think that is better than only the button and only the image.

**Comment by ekandreas** [comment]
Don't let the user think. Link it all.

**Comment by frozzare** [comment]
Solved by #138
