### ISSUE TITLE
A property that saves static html to the database

### ISSUE THREAD

**Issue by ekandreas** [wp-papi/papi#142]
Trying to update a property of type "html" but there seems to be no value stored to the page type after update field.
```php

papi_update_field($post->ID, 'message', 'this is a test <strong>value</strong>');
```

**Comment by ekandreas** [comment]
Version 3.0.0-beta1

**Comment by frozzare** [comment]
That's because html property dosen't save anything, it will only display html from the page type on the post edit page in wordpress admin. https://github.com/wp-papi/papi/blob/master/src/properties/class-papi-property-html.php

**Comment by ekandreas** [comment]
Ok, to bad. It should be really nice to have a prop to display non editable content to a page type.

**Comment by ekandreas** [comment]
The value is stored in the metadata table. Perhaps it should't be a big deal to output the value?

**Comment by frozzare** [comment]
Can you give a example of a real use case for that kind of property?

**Comment by ekandreas** [comment]
It works like a label.
In my case I'm handling the page types "magazine" with some cron-jobs. When the work is done a mail is sent to the owner of the post but it should also be nice if the log of the work is saved to the post and not anywhere else.

Another case could be a batch page type (that I use in another project). When the batch process is done a message could be attached to the post/page type. The value should not be editable. And really nice to apply html.

**Comment by frozzare** [comment]
This will not be saved to the database, but I think that you can do some crazy magic to get a input field to save the data to the database. But that isn't recommended.

```php
papi_property( [
  'title'    => 'Information',
  'type'     => 'html',
  'settings' => [
    'html' => '<p>Hello, world</p>'
  ]
] )
```

The update function will not recognize the custom html since it's not a real property.

What you are asking for is some kind of static content property, like html property but where can do update, delete and so, and yes that can be useful. The problem I can see if how the database content should be handled, if it just like html property just should display it even if looks broken and 
transfer of the responsibility of the broken output to the developer creating the page type.

I think it requires some thinking before doing this kind of property. Ping @rasmusbe

**Comment by rasmusbe** [comment]
I'm not sure if I understand the issue, but maybe this?

```php
papi_property( [
  'title'    => 'Information',
  'type'     => 'html',
  'settings' => [
    'html' => '<p>', get_post_meta( $_GET['post'], 'message', true ),'</p>'
  ]
] )
```

**Comment by ekandreas** [comment]
1. Create a property like this:
```
            papi_property( [
                'title' => 'Generator log',
                'slug'  => 'generator_log',
                'type'  => 'html',
            ] ),
```

2. Store som value to the property like so,
```
papi_update_field($post->ID, 'generator_log', '<strong>Magazine (64) generated at 2016-01-18 10:41:51</strong><br/>');
```

3. Take a look in the database! There's a value stored to the meta data.
![screen shot 2016-01-18 at 10 51 32](https://cloud.githubusercontent.com/assets/1794603/12388164/84d4d406-bdd1-11e5-9cf0-2642792dbae9.png)

4. wp-admin shows nothing as the papi property "settings/html" is empty. Why not use the meta data?

**Comment by ekandreas** [comment]
So my feature request is like: If nothing in settings/html on the property check if there's something in the fields meta value that could be rendered.

**Comment by frozzare** [comment]
As I described earlier the html property is only for displaying static html from a page type on the post edit page. It don't have connection to the data and you don't need a slug.

If we should do this we can't just make just one part of what you request.

**Comment by ekandreas** [comment]
This is how it looks like in our site / wp-admin when getting a generated message to the page type.

![screen shot 2016-01-18 at 17 31 12](https://cloud.githubusercontent.com/assets/1794603/12396754/6e59525a-be09-11e5-8f8d-f3757a6765dd.png)

**Comment by frozzare** [comment]
I think it's great to fix this, but should we allow all html and ignore if it breaks or not? Don't want issues like "papi breaks wordpress admin, please fix" or something like that and that's what you could create with this property.

Why I don't exists today is simple, no one has asked for a property like this. Papi is a open source project and we can't think of everything for everyone.

**Comment by frozzare** [comment]
New setting added to html property `save`, when this is true a hidden input field will be rendered and the value will be saved, the html value from the database will be used instead of the html value from the settings array. It's up to developer if dangerous html tags will be saved.
