### ISSUE TITLE
Add new property options that can turn on/off add, update, import, export, delete and read

### ISSUE THREAD

**Issue by frozzare** [wp-papi/papi#143]
This could be a cool feature that each property could have, new options that can disable add, update, import, delete and read (`get_field`). All options should be `true` as default and that won't break backward compatibility.

For example you could have static content for a property that you update from `papi_get_update_field` but you don't want it be updated when you save a post in the WordPress admin.

What it should be called can we discuss. Maybe something like this:

- `addable` or `can_add`
- `exportable` or `can_export`
- `deleteable` or `can_delete`
- `importable` or `can_import`
- `readable` or `can_read`
- `updateable` or `can_update`

Maybe we need some filters for this.

Example:

```php
// Disable update.
papi_property( [
    'slug'       => 'name',
    'title'      => 'Name',
    'type'       => 'string',
    'updateable' => false
] );

// Should return false since update is disabled. (or a WP_Error?)
papi_update_field( $post_id, 'name', 'Fredrik' );
```

### Checklist

- [ ] `addable`
- [ ] `exportable`
- [ ] `deleteable`
- [ ] `importable`
- [ ] `readable`
- [ ] `updateable`

**Comment by frozzare** [comment]
Descriptions of the different states:

#### Addable

When it's set to `false` the value will not be saved to the database. It will still render in the WordPress admin and will return `null` when using `papi_get_field`. It will not prevent `add_post_meta`.

#### Exportable

When it's set to `false` the value cannot be exported.

#### Deleteable

When it's set to `false` the value cannot be deleted using `papi_delete_field`. It will not prevent `delete_post_meta`.

#### Importable

When it's set to `false` the value cannot be imported.

#### Readable

When it's set to `false` the return value of `papi_get_field` will be `null`

#### Updateable

When it's set to `false` the value cannot be updated with `papi_update_field`, it will also prevent the value being saved to the database when click publish in the WordPress admin. It will not prevent `update_post_meta`.

**Comment by frozzare** [comment]
@rasmusbe thoughts?

**Comment by rasmusbe** [comment]
Sound like a good enhancement. 

I also think a great use would be to make some fields only updateable for some users, but readable for all by setting the value to a function

```
papi_property( [
    'slug'       => 'name',
    'title'      => 'Name',
    'type'       => 'string',
    'updateable' => can_the_user_change_the_name()
] );

function can_the_user_change_the_name() {
   return current_user_can('administrator');
}
```

**Comment by frozzare** [comment]
Yeah. Do you think that we should return a `WP_Error` instead of false? For example `papi_update_field` has some return false today and it maybe kind of hard to figure out why false is returned. It kind of like post meta functions today.

**Comment by rasmusbe** [comment]
Yes, that might be a good idea. And I guess that a function to check if the property can be updated is needed as well

**Comment by frozzare** [comment]
Moving this to v3.2.0 since it's kind of big and should not be rushed.

**Comment by frozzare** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;42RrQx9J&#x2F;75-updateable"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Updateable</a>

**Comment by frozzare** [comment]
I think is better to open up this issue again when this is something people needs instead of adding it and none is using it. I haven't had situations where I need this functionality (yet).
