### ISSUE TITLE
Custom property, getting saved data

### ISSUE THREAD

**Issue by danfri86** [wp-papi/papi#144]
Papi version 2.4.10

I'm creating a custom property for Google Maps that has three input fields for the values. My values gets saved and exists in the database but I can't receive them when I'm on my created post in admin and I'm probably doing something wrong. Give me a hand?

My html function in admin:

    public function html() {
      // Get values
      $value = $this->get_value();
      ?>

      <input type="search" id="<?php echo $this->html_id() ?>-search" name="<?php echo $this->html_name(); ?>[address]" value="<?php echo $value->address; ?>" />

      <div id="<?php echo $this->html_name(); ?>" class="map-canvas"></div>
    
      <p><input type="text" id="<?php echo $this->html_id() ?>-info-title" name="<?php echo $this->html_name(); ?>[info][title]" value="<?php echo $value->info->title; ?>" /></p>

      <p><textarea id="<?php echo $this->html_id() ?>-info-text" name="<?php echo $this->html_name(); ?>[info][text]"><?php echo $value->info->text; ?></textarea></p>
  
    <?php
    }

My $value variable is empty and if I print_r($this) I can't see my values even though I can see them in the database.

**Comment by frozzare** [comment]
`get_value` will not return `<?php echo $this->html_id() ?>-info-title` , `<?php echo $this->html_id() ?>-info-text` or `<?php echo $this->html_id() ?>-search`.

Would recommend you do a html array `<?php echo $this->html_id() ?>[search]`. Then `get_value` will return a array.

**Comment by danfri86** [comment]
In the name-attributes I already have arrays. I now changed my name attributes to `<?php echo $this->html_name(); ?>[map][address]; ?>`, `<?php echo $this->html_name(); ?>[map][info][title]; ?>` and `<?php echo $this->html_name(); ?>[map][info][text]; ?>` and `get_value` is still returning empty.

**Comment by frozzare** [comment]
You have to change the convert type (docs isn't up to date about this, will create a doc issue about this and fix it to next release), default convert type is string that's why you get a empty value.

Put this in your class and it will get you a object value.

```php
public $convert_type = 'object';
```

**Comment by danfri86** [comment]
Very nice, that did the job. Thank you.
