### ISSUE TITLE
Nested repeaters and flexibles

### ISSUE THREAD

**Issue by erikostling** [wp-papi/papi#146]
Requesting the ability to nest repeaters/flexibles in other repeaters/flexibles.

**Comment by frozzare** [comment]
No, I don't think that's good, if you need that Papi isn't right for you.

**Comment by erikostling** [comment]
Ok, thanks for quick reply, but would you mind elaborating on why you don't find it good? I'm very keen on migrating from ACF to PAPI, however the lack of this functionality makes me wonder how I'd solve certain tasks.

**Comment by rasmusbe** [comment]
Do you have any good examples where repeaters in repeaters is required?

**Comment by erikostling** [comment]
Well whenever there is need to arrange rows of fields in groups basically. It could be a page with X number of documents listed under Y number of headings for instance.

In the case of repeaters nested in flexibles I can see many more use cases due to the nature of the flexible field.

Would you say that nesting repeaters in repeaters is bad design practice? And how would you suggest solving grouping fields otherwise? Creating sub pages?

**Comment by frozzare** [comment]
I think that repeaters in repeaters is a bad design practice and it will get messy in the admin, also I think it's bad for editors so I have no plan to add this kind of support for Papi.
