### ISSUE TITLE
Description to box

### ISSUE THREAD

**Issue by ekandreas** [wp-papi/papi#147]
Sometimes I would like to add a description to the metabox in $this->box(...).
Sure, I can use the HTML-prop to accomplish this but perhaps it would be nice to add a description to the metabox for the users?
Eg,
```php
$this->box([
    'title' => 'My Title',
    'description' => 'Another description to the metabox for users',    
    papi_property([
            ...
        ],
]);

**Comment by frozzare** [comment]
You can use either divider property or html property to solve this so I don't see any point to add this kind of functionality since there are more than one way to solve this and don't forget that all properties can have a unique description.

**Comment by ekandreas** [comment]
Divider and html is a property. What I request is a meta box descriptor so announce the metabox to users.

**Comment by ekandreas** [comment]
I thought it would be a better user experience to get a overview of the metabox purpose. But there is no such thing i WP so...

**Comment by frozzare** [comment]
Well, it wouldn't be a real description for a meta box since WordPress don't have anything like this and it would like like html or divider even if you add description to meta box. So it would be the same thing as adding a property with the text.

**Comment by ekandreas** [comment]
Nope!
