### ISSUE TITLE
papi_tab not working

### ISSUE THREAD

**Issue by canufeelit** [wp-papi/papi#148]
Hi,

First, thank you for the hard work. Papi 3 is awesome.

Now to the point of my problem. I am upgrading from v1.4 to 3.0 but my tabs are not working. The first step was to go and see the example in the docs. Following this example [here](https://wp-papi.github.io/docs/api.html#papi_tab) is not working. I get the 'My meta box' and the tab 'Background' inside it is blank. No fields are rendered on this tab ([example](https://i.imgsafe.org/efcf1d9.png)).
There are no php errors. So I don't know what the problem might be.
Also, I think there's a typo in the `return papi_tabs` because there is no function with that name.

Thanks.

**Comment by frozzare** [comment]
Do you have any example code?

**Comment by canufeelit** [comment]
Yeah, sure.

[services-page.php](https://gist.github.com/canufeelit/d344ea204bb94d61cc51)
[video](https://gist.github.com/canufeelit/3f39fe59ad59a58899c4)

All of the code is from the examples.

**Comment by frozzare** [comment]
Yeah, it looks broken. Thanks for your bug report!

**Comment by frozzare** [comment]
This will be out in 3.0.1 that will be out in a few days. If you can't wait I would recommend to copy paste this file https://github.com/wp-papi/papi/blob/c1a1e327b13d173065bc7a0fed5e1e0b109af047/src/core/class-papi-core-tab.php

I have also added tests for this so we can cache this if it would break in the feature.

**Comment by canufeelit** [comment]
I will wait for the update.

Thank you very much.

**Comment by frozzare** [comment]
v3.0.1 is out now https://github.com/wp-papi/papi/releases/tag/v3.0.1
