### ISSUE TITLE
Add vertical boxes support

### ISSUE THREAD

**Issue by vinkla** [wp-papi/papi#159]
It would be nice if we could have the option to customize the boxes like this:

<img width="965" alt="screen shot 2016-03-02 at 6 08 24 pm" src="https://cloud.githubusercontent.com/assets/499192/13468272/2bdf0bb6-e0a2-11e5-8d7c-b30fbbd4de50.png">

**Comment by frozzare** [comment]
Yeah, that would be nice. When doing this it's important to test so all properties looks good, testing the different layout options for properties that has this setting, for example flexible and repeater.

**Comment by frozzare** [comment]
This will be out in `v3.1.0`. You can set this on box and property level. All properties will inherit it from the box if the default value isn't matched. Setting a property to horizontal (with sidebar) layout when the box has vertical layout will not work.

Box:

```php
$this->box( [
  'title'  => 'Content',
  'layout' => 'vertical'
], [] );
```

Property:

```php
papi_property( [
  'title'  => 'Name',
  'type'   => 'string',
  'layout' => 'vertical'
] );
```

**Comment by vinkla** [comment]
![shaun-the-sheep-movie-not-my-gif-2016-oscar-nominations-tIeCLkB8geYtW](https://camo.githubusercontent.com/09b6d44863f23bed3630cd8017c214c5d7844b97/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f744965434c6b423867655974572f67697068792e676966)
