### ISSUE TITLE
Add map property

### ISSUE THREAD

**Issue by vinkla** [wp-papi/papi#160]
It would be nice if we could add a map property to Papi. Maybe with Google Places?

**Comment by frozzare** [comment]
It would be nice if it was standalone and not in core, I don't all sites that use map is using Google, the maybe using here something else.

You could look at the old one to start with if you like to create a Google Maps property.

**Comment by vinkla** [comment]
Why does it matter if we have it as a standalone component vs having it in core? IMO I think it would make it easier to use Papi if it comes out of the box.

**Comment by frozzare** [comment]
It matters, I don't think map is a good property to have in the core, for example you maybe want here map in papi and not google map and if something like this would be merged someone need to maintain it.

**Comment by vinkla** [comment]
Okay, sounds fare. Adding it to the docs would be nice though. New page with standalone properties.

**Comment by frozzare** [comment]
Yes, but the deprecated v1 google maps property don't work with v3 :wink:

**Comment by vinkla** [comment]
Aah okay, to bad :sad: That property is a real game changer for me if I want to move away from ACF.

**Comment by frozzare** [comment]
I don't think is too hard to take the old one and modify it so it works with v3 and the documentationen https://wp-papi.github.io/docs/custom_property.html

**Comment by vinkla** [comment]
Okay, I'll check it out. Thanks.
