### ISSUE TITLE
`add_new_label`not working for repeater property type.

### ISSUE THREAD

**Issue by richardsweeney** [wp-papi/papi#162]
### What I expected

The `add_new_label` for repeater property type doesn't appear to work.

### What happened instead

`'add_new_label' => __( 'Add new slide', 'msp' ),` was ignored. The text for the button to add a new row was still 'Add new row'

### Steps to reproduce

    <?php
    ...
    public function register() {
        $this->box( __( 'Carousell', 'msp' ), [ $this, 'register_carousell' ] );
    }

    public function register_carousell() {
        return [
            papi_property( [
                'type' => 'repeater',
                'title' => __( 'Carousel', 'msp' ),
                'add_new_label' => __( 'Add new slide', 'msp' ),
                'slug' => 'carousel',
                'sidebar' => false,
                'settings' => [
                    'items' => [
                        papi_property( [
                            'type'  => 'image',
                            'title' => __( 'Image', 'msp' ),
                        ] ),
                        papi_property( [
                            'type'  => 'string',
                            'title' => __( 'Button Text', 'msp' ),
                        ] ),
                        papi_property( [
                            'title' => 'Link',
                            'type'  => __( 'link', 'msp' ),
                        ] )
                    ]
                ]
            ] )
        ];
    }`

### What versions of software are you using?

Papi 3.0.2, WordPress 4.4.2

**Comment by frozzare** [comment]
`add_new_label` on repeater is a setting and you have it above setting array :)
