### ISSUE TITLE
Link property type always required

### ISSUE THREAD

**Issue by ekandreas** [wp-papi/papi#165]
### What I expected
Required field in the wp-admin should accept data for a link property.

### What happened instead
All fields for a link added but still papi locks the editor from saving the post with required data for link.

### Steps to reproduce
Add a property to a meta like
````
            papi_property( [
                'slug'  => 'external_source',
                'required' => true,
                'title' => 'Outgoing Link',
                'type'  => 'link',
            ] ),
```
Try to save the post and an error message stops the post from being updated.

The link property was ok in earlier versions.

### What versions of softwares are you using?

- Browser: Chrome, latest
- Papi: 3.0.3
- WordPress: 4.4.2

**Comment by frozzare** [comment]
This is now fixed in `3.x` branch. You can use it direct with `"wp-papi/papi": "3.x-dev#ed731e6e4f01c67c3549fa17277d1bd76e113928"` instead of waiting on `v3.0.4`.

**Comment by vinkla** [comment]
Or better yet, specify it with the branch alias `^3.1`.

**Comment by frozzare** [comment]
@vinkla no since `v3.1` is unstable and `v3.0.4` will be out before `v3.1`. So don't do that :)

**Comment by vinkla** [comment]
Don't use commits hash. It is bad practice.

**Comment by vinkla** [comment]
Better wait on the next release.

**Comment by frozzare** [comment]
It's not recommended to use unstable versions like you recommend.

**Comment by vinkla** [comment]
It is not recommended to target specific commit hashes.

**Comment by frozzare** [comment]
No, but better to use a stable version than a unstable version that isn't finished.

**Comment by vinkla** [comment]
Then add a branch alias instead. We shouldn't recommending bad practice.

**Comment by frozzare** [comment]
You shouldn't recommend to use a unstable version. It's very bad.

**Comment by vinkla** [comment]
It depends on the implementation really.

**Comment by frozzare** [comment]
The readme says that master branch is unstable where `v3.1.0` is.
