### ISSUE TITLE
Property datetime not working in a repeater

### ISSUE THREAD

**Issue by chrisvidal** [wp-papi/papi#166]
### What I expected
Property datetime available inside a repeater

### What happened instead
No datetime selection display a repeater but just a text field

### Steps to reproduce

    public function register() {
        $this->box( 'Event details', [
            papi_property( [
                'title'    => 'Event Details',
                'type'     => 'repeater',
                'settings' => [
                    'layout'    => 'table',
                    'limit'    => '5',
                    'items' => [
                        papi_property( [
                            'type'  => 'datetime',
                            'title' => 'Event Time',
                            'slug' => 'event_datetime',
                            'description'  => 'Event time'
                        ] )
                    ]
                ]
            ])
        ] );
    }

### What versions of softwares are you using?
- Browser: Chrome
- Papi: Version: 3.0.4
- WordPress: Latest

Javascript error : main.min.js?ver=4.4.2:13 Uncaught TypeError: this.pikaday is not a functiona.value @ main.min.js?ver=4.4.2:13

**Comment by frozzare** [comment]
Thanks for the issue, I have fixed this in `3.x` branch and this will be out today or tomorrow in `v3.0.5`.

**Comment by chrisvidal** [comment]
Thanks ! This plugin is really a pleasure to use !

**Comment by frozzare** [comment]
Thank you @chrisvidal!

**Comment by frozzare** [comment]
https://github.com/wp-papi/papi/releases/tag/v3.0.5

**Comment by chrisvidal** [comment]
Excellent ! thank you
