### ISSUE TITLE
Custom Papi Field type issue with JSON encoded strings.

### ISSUE THREAD

**Issue by richardsweeney** [wp-papi/papi#177]
My colleague wrote a custom field type for Google Maps.

The field type saves the address, lat and lng of the map as a single row. This is JSON encoded (by Papi) before it's added to the database which results in å ä ö being converted to u00e5 u00e4 u00f6 respectively.

The entities are not converted back when the value is retrieved from the database. Which I reckon is a bug :)

- Papi: 3.1.1
- WordPress: 4.5.3

The row from the postmeta table looks like this:

`{"address":"Torupsgatan 1D, 217 73 Malmu00f6 u00e5u00e4u00f6","lat":"55.5926892","lng":"12.965653999999972"}`

**Comment by frozzare** [comment]
Fixed in `3.x` branch and will be out in v3.1.2 soon!
