### ISSUE TITLE
Relationship field behaviour

### ISSUE THREAD

**Issue by richardsweeney** [wp-papi/papi#183]
With the post relationship field: when you add an object relationship, the object will disappear from the left-hand column and will be placed in the right-hand column.

This makes perfect sense to me. But, when the post is saved and the screen reloads the left-hand column is repopulated with all the objects again, including the objects that were selected (that is to say, the objects that were removed from the left-hand column).

The screenshot below shows the behaviour after the post is saved. 

![after the post is saved](https://cloud.githubusercontent.com/assets/761071/17507267/1b2ca7f2-5e0f-11e6-8303-cde81c7d0b2c.png)

- Papi: 3.1.6
- WordPress: 4.5.3

**Comment by frozzare** [comment]
Thanks, this is now fixed in 3.x branch and will be out in next patch release!
