### ISSUE TITLE
Small css fixes for repeater in flexible

### ISSUE THREAD

**Issue by rasmusbe** [wp-papi/papi#187]
![image](https://cloud.githubusercontent.com/assets/2124386/17665998/63b2a726-62fe-11e6-9704-95c8e069646a.png)

I have identified some small issues with the css for repeater in flexible that should make the user experience a bit better.

1. The border and margins are off.
2. Add a border to the left of a repeater in a flexible. And maybe use another gray color as background for the numbers and delete areas to make it clearer which row you are deleting. Not sure if it's good to introduce another color, but it might help.
3. Remove double border

**Comment by frozzare** [comment]
Thanks, will be out in next release.
