### ISSUE TITLE
Bug with admin menu with several custom post types

### ISSUE THREAD

**Issue by slaxxarn** [wp-papi/papi#190]
### What I expected
Excepted to get the real Add new {post type name} title on create new post/post-type page
### What happened instead
Got Add new {previous post types name}, the one that i was on in the step before
### Steps to reproduce
Create a custom post type and go to add new post, then go to add new {your created post type} in the admin menu and see that the title is all wrong (or the other way around, works in both direction). It's just the title that is wrong, the page is loading the correct template.

### What versions of softwares are you using?

- Browser: Firefox 48
- Papi: Version 3.1.12
- WordPress: 4.6.1

**Comment by frozzare** [comment]
Fixed in `3.x` and will be out soon.
