### ISSUE TITLE
[bug] - dot files

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#193]
### Bug description

Some weird characters are printed on every page (front and admin). Digging further, I noticed the content of `.DS_Store` was displayed. Looks like dot files are also parsed in directories: https://github.com/wp-papi/papi/blob/master/src/lib/core/io.php#L54-L64 

### What I expected

Skip dot files when parsing directories. 

### Steps to reproduce

- Create any dot file in a directory parsed by Papi and write any content in it. 
- Load any WordPress page, content will be output at the top of the source code.

### What versions of softwares are you using?

- Papi: dev-master
- WordPress: 4.6.1

**Comment by frozzare** [comment]
Thanks, never thought of this since I don't have dot files in the same folder as page types.

**Comment by nlemoine** [comment]
Never had before either. Thanks for the fix! 👍
