### ISSUE TITLE
[bug] - Property/Text : nl2br

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#199]
### What happened

Using a regular text field: 
```php
papi_property( [
	'title'       => 'Some text',
	'type'        => 'text',
	'slug'        => 'some_text',
]),
```
When using `the_papi_field`,  line breaks should be converted to `<br />` tags by default but are actually escaped: `&lt;br /&gt;`

### What I expected

Line breaks should be converted to `<br />` tags but should not be escaped. 

### Problem

There's a contradiction with text property settings. 

In order to allow `nl2br` to work, `allow_html` has to be set to `false`: https://github.com/wp-papi/papi/blob/master/src/properties/class-papi-property-text.php#L19

But if `allow_html` is set to `false`, the value is escaped: https://github.com/wp-papi/papi/blob/master/src/properties/class-papi-property-text.php#L57

Thus escaping the `<br />` tags produced by `nl2br`.

### What versions of softwares are you using?

- Papi: latest
- WordPress: latest

**Comment by frozzare** [comment]
Thanks, fixed and will be out shortly.
