### ISSUE TITLE
[bug] - Editor property

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#201]
### Description

When using more than one `editor` property in a flexible, the first one is but the others editors are not rendered correctly. They are stuck on the "text" tab, "visual" tab can't be clicked. 

### Steps to reproduce

```php
papi_property( [
  'title'    => 'Flexible',
  'slug'     => 'my_flexible_slug',
  'type'     => 'flexible',
  'settings' => [
    'items' => [
      [
        'title' => 'Posts',
        'items' => [
          papi_property( [
            'type'  => 'editor',
            'title' => 'Title',
            'slug'  => 'my_string_slug'
          ] ),
          papi_property( [
            'type'  => 'editor',
            'title' => 'Post',
            'slug'  => 'my_post_slug'
          ] )
        ]
      ],
    ]
  ]
] )
```

### What versions of softwares are you using?

- Browser: Chrome latest
- Papi: dev-master
- WordPress: latest

**Comment by frozzare** [comment]
Is this only a problem in master branch or a problem with the latest stable version? Note that master branch is unstable and should not be used on real sites :)

**Comment by nlemoine** [comment]
Sorry, confirmed with 3.1.15 ;)

**Comment by frozzare** [comment]
<img width="673" alt="skarmklipp 2016-10-23 12 57 51" src="https://cloud.githubusercontent.com/assets/14610/19625708/62b4a5e2-9920-11e6-8d6d-bd851d15ea70.png">

Isn't this right? Both are rendered with `visual` tab and both `text` tabs can be clicked. Tested with `3.x` branch (that will be 3.1.16).

**Comment by nlemoine** [comment]
I didn't think the layout could be involved but the bug only occurs when `layout` is set to `vertical`:

```php
papi_property( [
  'title'    => 'Flexible',
  'slug'     => 'my_flexible_slug',
  'type'     => 'flexible',
  'settings' => [
    'layout' => 'vertical',
    'items' => [
      [
        'title' => 'Posts',
        'items' => [
          papi_property( [
            'type'  => 'editor',
            'title' => 'Title',
            'slug'  => 'my_string_slug'
          ] ),
          papi_property( [
            'type'  => 'editor',
            'title' => 'Post',
            'slug'  => 'my_post_slug'
          ] )
        ]
      ],
    ]
  ]
] )
```

**Comment by frozzare** [comment]
Yeah, that did cause the bug. The problem was that it assume that it was a `tbody` around both properties and not a single on when vertical layout is used. So the editors did get the same id and that isn't ok with tinmyce.

Fixed in `3.x` and `master` and will be out in next `3.x` versions coming soon.

**Comment by nlemoine** [comment]
Thanks! 👍

**Comment by frozzare** [comment]
Is this only a problem in master branch or a problem with the latest stable version? Master branch is unstable and should not be used.

**Comment by nlemoine** [comment]
The issue has already been resolved.

**Comment by frozzare** [comment]
@nlemoine the email did get stuck on my phone last week, sorry for that.

**Comment by nlemoine** [comment]
No problem ;)
