### ISSUE TITLE
Link field not working in WP 4.7

### ISSUE THREAD

**Issue by pjbtwo** [wp-papi/papi#207]
### What I expected
Expected to add a link to a page

### What happened instead
In link pop-up window you must specify open in new window for link to work. If I leave checkbox unchecked, no link is added. Console reports javascript error:

VM949:24 Uncaught ReferenceError: target is not defined(…)
(anonymous function) @ VM949:24
c @ load-scripts.php?c=0&load[]=hoverIntent,common,admin-bar,heartbeat,autosave,wp-ajax-response,jquery…:112
value @ link.js:146
dispatch @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.7:3
r.handle @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.7:3 

### Steps to reproduce
Try to add a link to any page or post with WP v 4.7

### What versions of softwares are you using?

- Browser: Chrome 54.0.2840.98
- Papi: 3.1.17
- WordPress: 4.7

**Comment by frozzare** [comment]
Sounds like a issue with 4.7, will look at this when I get some time to do it.

**Comment by pjbtwo** [comment]
I think I found something. It seems wpLink.getAttrs() doesn't return target if the checkbox is left unchecked. I put a little check in render() method of Link in link.js to see if target is present or not. If not present I set it to '_self' else I leave it. Seems to have fixed the problem but I leave it up to you to do it correct in source files.

**Comment by frozzare** [comment]
@pjbtwo fixed in `3.x` branch by @rasmusbe, new patch release will be released soon.

**Comment by frozzare** [comment]
https://github.com/wp-papi/papi/releases/tag/v3.1.18
