### ISSUE TITLE
Box ID key

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#215]
I don't know if this behavior is intended or a bug. 

### What I expected

Keys usually don't contain special characters. 

### What happened instead

The `box` ID meta key used by Papi when none is provided can contain accents, quotes, etc.

### Steps to reproduce

```php
var_dump( strtolower( papi_f( papi_underscorify( papify( 'string with quotes’ and accènts' ) ) ) ) );
```
### What versions of softwares are you using?

- Papi: 3.1.18
- WordPress: 4.7.2

**Comment by frozzare** [comment]
Not intended and not tested. Let's fix it.
