### ISSUE TITLE
File property: notice undefined property

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#217]
### Description

Undefined property notice.

### Steps to reproduce

- Add a `file` property
- Load and select a file (an mp4 video in my case, don't know if it matters)
- Save

Page should now show a notice mentioning "undefined property on line 187" (in 3.1.18, [line 185 on master](https://github.com/wp-papi/papi/blob/master/src/properties/class-papi-property-file.php#L185)) because, for a reason I didn't check, `file` isn't set. 

### What versions of softwares are you using?

- Papi: 3.1.18
- WordPress: 4.7.2

**Comment by frozzare** [comment]
Hm. Can't reproduce this with a image file or a excel file. But we can add a check that checks if `file->file` exists before it's used.

**Comment by nlemoine** [comment]
I checked again, this issue happens with an mp4 file. You can download a sample one [here](http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4).

**Comment by frozzare** [comment]
Looks like the file property value isn't set on some files, since `basename` works with urls we can just set file property value to url and get the same output.
