### ISSUE TITLE
Dropdown property doesn't work with numeric keys

### ISSUE THREAD

**Issue by rasmusbe** [wp-papi/papi#225]
### What I expected
The saved values in admin

### What happened instead
Invalid values in admin

### Steps to reproduce
```
papi_property(
	[
		'title'    => __( 'File list', 'bbws-admin' ),
		'type'     => 'dropdown',
		'slug'     => 'list',
		'settings' => [
			'items' => [
				'Hello' => 1,
				'World' => 2
			]
		]
	]
)
```

Select World and save. Saved value is 2. Displayed value in admin is Hello.

### What versions of softwares are you using?

- Papi: latest
- WordPress: latest

**Comment by sasimon** [comment]
It's actually more general than that. The dropdown does not work with associative arrays, period. Even if the keys and values are both strings, the values will not save to the database.
