### ISSUE TITLE
Checkbox state on page load

### ISSUE THREAD

**Issue by JeroenKnockaert** [wp-papi/papi#226]
### What I expected
I expected checked checkboxes to be checked when loading the page.
### What happened instead
On page load every checkbox is unchecked by default.
### Steps to reproduce
When you open a page that has checkboxes, all of them are shown as unchecked. When you save the page. They also get saved as unchecked.

### What versions of softwares are you using?

- Browser: Google Chrome
- Papi: WP Papi 3.2.0-beta1
- WordPress: 4.7.3

**Comment by frozzare** [comment]
Hi,

Do you mean checkbox property or bool property? They both use checkboxes and both should work. Checkbox property works with Papi 3.2.0-beta1 since I run beta1 in production with checkbox property.

If you have any code examples or a better "steps to reproduce" it may help.

**Comment by frozzare** [comment]
ping @JeroenKnockaert

**Comment by JeroenKnockaert** [comment]
@frozzare When I want to edit a page, the page always loads with unchecked checkboxes.
So for example: when I want to change a title of a page, when saving the changes, it will also override the previous state of the checkboxes, meaning they will always be unchecked.
Unless I check them all by myself everytime I need to edit the content..

**Comment by frozzare** [comment]
Hi,

This project is not maintained anymore since I have stepped down as a the core maintainer. You can read more about this in the last big release. The project will no die or disappear but no new version will be created until a new maintainer steps in.
