### ISSUE TITLE
Adding Papi Page Type as an ACF Location

### ISSUE THREAD

**Issue by Log1x** [wp-papi/papi#234]
Hi.

I'm trying to add Papi Page Type's as a custom location in ACF but am unable to get WP Papi to return my registered Page Types. Possibly there's a function I'm missing to pull the data I'm wanting?

```
add_filter('acf/location/rule_types', function ($choices) {
    $choices['Page']['papi_type'] = 'Papi Type';
    return $choices;
});
```

```
add_filter('acf/location/rule_values/papi_type', function ($choices) {
    $entry_types = papi_get_all_entry_types();

    if ($entry_types) {
        $entry_types = array_map(function($entry_type) {
            return [
                'id'   => $entry_type->get_id(),
                'name' => $entry_type->name,
                'type' => $entry_type->get_type(),
            ];
        }, $entry_types);

        foreach ($entry_types as $entry_type) {
            $choices[$entry_type['id']] = $entry_type['name'];
        }
    }

    return $choices;
});
```

```
add_filter('acf/location/rule_match/papi_type', function ($match, $rule, $options) {
    if (!$options['post_id']) {
        return false;
    }

    $papi_type = papi_get_page_type_id($options['post_id']);
    $selected_type = (string) $rule['value'];

    if ($rule['operator'] == '==') {
        $match = ($papi_type == $selected_type);
    }

    if ($rule['operator'] == '!=') {
        $match = ($papi_type != $selected_type);
    }

    return $match;
});
```

I'm mainly unsure of my usage of `papi_get_page_type_id()` and `papi_get_all_entry_types()`. It seems like it'd work, but neither function are returning any values. With neither of them returning a value, I attempted to wrap my filters in a `papi/init` action, but that didn't change anything.

My filters above are based on the [ACF Custom Location Rules](https://www.advancedcustomfields.com/resources/custom-location-rules/) documentation.

Thanks in advance for any help on this.

**Comment by frozzare** [comment]
I have no idea how ACF works but you can use `papi_get_all_entry_types` to get all registered page/option/taxonomy types and if you only want page types you can use `papi_get_all_page_types`.

Both functions will return a array of entry types as in your second example if you have register a directory with Papi.

Since I don't know how ACF works I can't tell how you should get Papi and ACF work together. It's two plugin you shouldn't use at the same time. Maybe you can but I wouldn't use the together. I created Papi because I wanted a developer friendly plugin to create custom fields and page type and not a plugin where I was locked to a UI. So sorry, I can't help you with ACF.

**Comment by Log1x** [comment]
Thanks for the reply. `papi_get_all_page_types` should do the trick. I'll update this post once I try it in the event someone stumbles upon this at some point.

**Comment by Log1x** [comment]
It seems ACF's `add_filter('acf/location')` is firing before Papi loads all of it's page types.

Is there a convenient action/filter I can use so I can make it load after Papi does instead?

I tried `papi/init` but didn't get anywhere with it. If `papi/init` is my only option, is there a way to manually invoke Papi so I can get a result from `papi_get_all_page_types()`?

**Comment by frozzare** [comment]
You should manually invoke Papi since it can break things. Maybe you should try to load ACF later.

I can't be of any more help since I don't know how ACF works and will not learn ACF.

**Comment by Log1x** [comment]
Got it all working. Thanks a lot for your help. Here's the necessary filters if anyone stumbles upon this via Google in the future:

```
add_filter('acf/location/rule_types', function ($choices) {
    $choices['Papi']['papi_page_type'] = 'Page Type';
    return $choices;
});
```

```
add_filter('acf/location/rule_values/papi_page_type', function ($choices) {
    $page_types = papi_get_all_page_types();

    if ($page_types) {
        $page_types = array_map(function($page_type) {
            return [
                'id'   => $page_type->get_id(),
                'name' => $page_type->name
            ];
        }, $page_types);

        foreach ($page_types as $page_type) {
            $choices[$page_type['id']] = $page_type['name'];
        }
    }

    return $choices;
});
```

```
add_filter('acf/location/rule_match/papi_page_type', function ($match, $rule, $options) {
    if (!$options['post_id']) {
        return false;
    }

    $page_type = papi_get_page_type_id($options['post_id']);
    $selected_type = (int) $rule['value'];

    if ($rule['operator'] == '==') {
        $match = ($page_type == $selected_type);
    }

    if ($rule['operator'] == '!=') {
        $match = ($page_type != $selected_type);
    }

    return $match;
}, 10, 3);
```

The above is only for Page Types, but could very easily be modified for other Papi types.
