### ISSUE TITLE
_papi_page_type not assigned when importing pages

### ISSUE THREAD

**Issue by Log1x** [wp-papi/papi#237]
### What I expected
When importing posts/pages to a new database and theme with `add_filter('papi/settings/show_standard_page_type_page', '__return_true');` -- I expect the Pages to be imported as normal pages and for WP Papi to automatically assign the meta key `_papi_page_type` to `papi-standard-page-type`

### What happened instead
All imported pages are my custom Papi Page Type when imported instead, and if I try to change my Page Type to "Standard page"-- it doesn't work.

See my GIF of this happening [here](https://log1x.com/screenshots/2017-07-07_20-05-30_JxIr3.gif).

### Steps to reproduce
- Use `add_filter('papi/settings/show_standard_page_type_page', '__return_true');`
- Create a custom Papi Page
- Import existing post/pages to your fresh database
- See that `_papi_page_type` isn't being assigned to the pages and they aren't able to be manually changed.

### What versions of softwares are you using?

- Browser: Firefox 54
- Papi: 3.2.beta2 (dev-master)
- WordPress: 4.8

**Comment by frozzare** [comment]
Thanks for your issue, I'm on vacation for a couple of weeks so I will not do anything work on Papi right now. I only work on Papi when I have time at work nowadays.

If you could send a pull request it would be awesome.

**Comment by Log1x** [comment]
Wouldn't mind doing the PR, just have no idea where to start.

I'm guessing we need a conditional somewhere very similar to [L30 of class-papi-admin-page-type-switcher.php](https://github.com/wp-papi/papi/blob/de87dd5e3f46070289b53b12f9f59d8ef8d91337/src/admin/class-papi-admin-page-type-switcher.php#L30).

One thing to note is the filter show `Standard Page` as seen here:
![Screenshot(https://log1x.com/screenshots/2017-07-07_21-04-56_fvRV5.png)

But when editing it shows the wrong papi page type as seen in my GIF as well as this screenshot:
![Screenshot 2](https://log1x.com/screenshots/2017-07-07_21-05-39_YFXM7.png)

Please don't let me distract you from your vacation, but if you get a second-- I think I can fix this if you can point me in the right direction.

**Comment by frozzare** [comment]
Sorry for the late reply;

Standard page don't have any meta value so no need to set `_papi_page_type` to `papi-standard-page` when importing. If a meta key don't exists it will fallback to standard type and it may be a problem with the fallback.

Have you tried the latest `dev-master`? Because I think this is a problem that I did fix, but maybe it's broken again.

It you would like to dig into the page type switcher there are a admin file for that.
