### ISSUE TITLE
CSS issues with flexible label (row layout) 

### ISSUE THREAD

**Issue by frozzare** [wp-papi/papi#256]
### What I expected

Perfect alignment 

### What happened instead

![1yab4iwsfo1bwopjp8xgic5qgun1ahxlijov_ouybp1qna0q98hxhr6m5jdnwv-bzvwzcdyjipb4xd-lmzmivt0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/14610/46800253-6844fa80-cd57-11e8-9d88-297f65c6304f.png)

### Steps to reproduce

Create a box with this content and the css issue should appear.

```php
$this->box( [
    'title' => 'Sections',
    papi_property( [
        'sidebar'  => false,
        'slug'     => 'sections',
        'title'    => 'Sections',
        'type'     => 'flexible',
        'settings' => [
            'layout' => 'row',
            'items'  => [
                [
                    'title' => 'Post',
                    'slug'  => 'post-row',
                    'items' => [
                        papi_property( [
                            'title'    => 'Post',
                            'type'     => 'post',
                            'slug'     => 'post',
                        ] ),
                    ],
                ],
            ],
        ],
    ] ),
] );
```

### What versions of softwares are you using?

- Browser: Latest chrome
- Papi: 3.3.x-dev
- WordPress: 4.9.8

**Comment by fraktalize** [comment]
I could dig into this!

**Comment by fraktalize** [comment]
PR here: https://github.com/wp-papi/papi/pull/260
