### ISSUE TITLE
Box's content disappears

### ISSUE THREAD

**Issue by s3rgiosan** [wp-papi/papi#38]
I have a page type with an image repeater and when I create a new page of this type, I see the box and can select multiple images. The problem is that when I publish the page, the selections that I did not appear. In fact, the contents of that box is empty.

I can see, however, the images ID's and description in the postmeta database table.

```php  
public function register() {
        $this->box( 'Images', [
            $this->property( [
                'type'     => 'repeater',
                'title'    => 'Images',
                'slug'     => 'images',
                'sidebar'  => false,
                'settings' => [
                    'items' => [
                        $this->property( [
                            'type'  => 'image',
                            'title' => 'Image'
                        ] ),
                        $this->property( [
                            'type'  => 'text',
                            'title' => 'Image description'
                        ] )
                    ]
                ]
            ] )
        ] );
}
``` 

Am I missing something here?

**Comment by frozzare** [comment]
Hi, which version are you using?

This works for me with version 1.1.0 (or 1.x branch)

**Comment by s3rgiosan** [comment]
Hi,
I'm using this version [v1.1.1](https://github.com/wp-papi/papi/releases/tag/v1.1.1).
I'm using it in a multisite installation with WPML, in case it matters.

**Comment by frozzare** [comment]
I think that WPML is the problem since this work for me on a multisite.

**Comment by s3rgiosan** [comment]
I think that the problem is in the following if/else block (`includes/lib/property.php`):
```php
if ( _papi_get_qs( 'lang' ) != null ) {
	$render = $property->lang === strtolower( _papi_get_qs( 'lang' ) );
} else {
	$render = true;
}
```
With WPML the _papi_get_qs function will always return a lang string (in my case `pt-pt` and `en`) and if I want to use the same property definition for all the languages, I cannot because of this.
A possible solution could be:

```php
	$defaults = array(
		//...
		'lang'         => false,
		//...
	);
//...
	if ( $property->lang !== false && _papi_get_qs( 'lang' ) != null ) {
		$render = $property->lang === strtolower( _papi_get_qs( 'lang' ) );
	} else {
		$render = true;
	}
```

**Comment by frozzare** [comment]
I can merge #41 so long as it does not become WPML specific stuff since Papi will never support WPML.

**Comment by frozzare** [comment]
This fix will be in the next minor version of Papi
