### ISSUE TITLE
Page types - Remove meta box misleading documentation

### ISSUE THREAD

**Issue by s3rgiosan** [wp-papi/papi#39]
Hi,
In the documentation, the section "[Page types - Remove meta box](http://papi.readthedocs.org/en/latest/manual/page-types.html#remove-meta-box)" makes reference to the [remove meta box](http://codex.wordpress.org/Function_Reference/remove_meta_box#Parameters) Codex page, but I think that you want to make reference to [remove post type support](http://codex.wordpress.org/Function_Reference/remove_post_type_support) page.

**Comment by frozzare** [comment]
Please report this issue in the right repository. https://github.com/wp-papi/docs
