### ISSUE TITLE
Repeater property with WP editor doesn't work

### ISSUE THREAD

**Issue by s3rgiosan** [wp-papi/papi#47]
Hi,

I'm trying to use a repeater with a WP editor and it doesn't work. The cloned editors do not respond to click events, only when I publish/update the page. I think that the problem is the duplicate ID's.

Regards,
Sérgio

**Comment by frozzare** [comment]
Hi, yes this does not work. There is no quick fix this so I don't know when I have a good solution that solves this.

**Comment by frozzare** [comment]
This will be out in v1.3.0.
