### ISSUE TITLE
Page Type not registered as specific Page Type

### ISSUE THREAD

**Issue by EkAndreas** [wp-papi/papi#49]
If you have no properties registered to a specific Page Type and create a new page, that specific page will not have the page type set.
To recreate the bug:
1. Create a new Page Type with no properties registered, eg PT1
2. In wp-admin, add a new page and choose the newly created page type, eg PT1.
3. Save the page and go back to the list of pages.
4. The newly created page will not have the new page type set, should have PT1?

**Comment by EkAndreas** [comment]
This code will work: 
```php
<?php

class Fragment_Page_Type extends Papi_Page_Type
{
    public function page_type()
    {
        return [
            'name'        => 'Fragment',
            'description' => 'Part of other pages for reuse',
            'template'    => 'templates/fragment.php',
            'post_type'   => array( 'page' ),
        ];
    }

    public function register()
    {
        $this->box( 'Description', [
            $this->property( [
                'type'  => 'text',
                'title' => 'Description',
                'slug'  => 'description'
            ] ),
        ] );
    }
}```

**Comment by EkAndreas** [comment]
This code wont work:
```php
<?php

class Fragment_Page_Type extends Papi_Page_Type
{
    public function page_type()
    {
        return [
            'name'        => 'Fragment',
            'description' => 'Part of other pages for reuse',
            'template'    => 'templates/fragment.php',
            'post_type'   => array( 'page' ),
        ];
    }
}```

**Comment by EkAndreas** [comment]
Should I try with a pull request?

**Comment by frozzare** [comment]
The problem is that no meta boxes is created and the hidden field is in the meta boxes so the best would be to move the output of "_papi_page_type" to the admin class and output it there in the form tag so it still can be fetch from the POST object.

Yes, you can try to do a pull request.

**Comment by EkAndreas** [comment]
Ahh, ok, quite simple then.
I think this could be a very good thing to fix because if you follow the "getting started", you get this result and you could quickly say that Papi didn't work as expected.

**Comment by frozzare** [comment]
Yes, I agree that this could be a good think to fix.

**Comment by frozzare** [comment]
@EkAndreas Will you try do a pull request or do you want me to fix this?

**Comment by EkAndreas** [comment]
Don't wait for me :-)
So, please, do it!

**Comment by frozzare** [comment]
@EkAndreas Can you test if the fix in master branch work?

**Comment by EkAndreas** [comment]
Will test now!

**Comment by EkAndreas** [comment]
Yes, the update to dev-master and a test confirms that a page type will work even without properties assigned to it when creating a new page. Thanks!
