### ISSUE TITLE
allow_html for text/string properties

### ISSUE THREAD

**Issue by sanklin** [wp-papi/papi#55]
It would be nice to enable html in the string/text (which is not an editor) properties, but not by default. So that you may use some html-markup.

**Comment by frozzare** [comment]
This require some rewrite of the saving logic and the property class. The big problem is when you hit save the property don't now which options it has. But I think it's time to change that, so before I can start the progress on this I have to rewrite the property logic a bit. But it's for the good :)

**Comment by frozzare** [comment]
I have fixed this so it will be out in next version of Papi.
