### ISSUE TITLE
Add `html_name` method to `Papi_Property` class

### ISSUE THREAD

**Issue by frozzare** [wp-papi/papi#63]
As discussed in https://github.com/wp-papi/papi/issues/62#issuecomment-101965786 it would be nice with a `html_name` method in `Papi_Property` class so you can do:

```
`<input name="' . $this->html_name( $subproperty ) . '" />`
```

With or without a sub property value. If empty value just return `$options->slug` value.

To get this working for a repeater I think it's best to send in a second argument that is a count value or have a standard how this kind of properties should implement the counter.

**Comment by frozzare** [comment]
@entr All core properties uses this method now :)

**Comment by entr** [comment]
Amazing. How long do you think until this gets into stable.

**Comment by frozzare** [comment]
Will try to get it out in the end of next week. My colleagues at work will test it during the week since they are using 1.3.0 in a new project.
