### ISSUE TITLE
SVG

### ISSUE THREAD

**Issue by danielforsberg** [wp-papi/papi#68]
Just started out with Papi. This is really good stuff!

I am using

```php
		$this->box(
			'Logo', [
				papi_property(
					[
						'type'        => 'image',
						'slug'        => 'page_logo'
					]
				)
			]
		);
```

And this works great except when I try to upload a svg. I have allowed svg with wordpress so it is not that.

The field in wp-admin just wont update when I choose a svg.

May this be an issue with Papi or am I missing something?

**Comment by frozzare** [comment]
Great that you like Papi! I have fixed this issue now, it was a old is image check that didn't allow svgs. I will create a new release soon with this fix and some other fixes.

**Comment by danielforsberg** [comment]
Thanks for a quick response!

Now you can add a svg, but when you update the page the uploaded svg disappears.

@frozzare

**Comment by frozzare** [comment]
Hm, it looks like `wp_get_attachment_metadata` don't work with svg. I will take a look at it.

**Comment by frozzare** [comment]
@danielforsberg Can you test if this fix is working? It's worked for me when i reload the page with a svg image.

https://github.com/wp-papi/papi/commit/df92cc04edab1d331f17e93f64b606e11e63b0ed

**Comment by danielforsberg** [comment]
@frozzare Yes this made it work correctly. Thanks for doing this in such short notice!

**Comment by frozzare** [comment]
Great! I released a patch version with this fix. https://github.com/wp-papi/papi/releases/tag/v2.1.1
