### ISSUE TITLE
papi on custom post type

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#70]
Hi, 

Is it possible to add papi properties to a custom post type? There's a `post_type` parameter on the box method but has no effect.

**Comment by frozzare** [comment]
It's possible. The documentation is wrong on just that part. A box on a page type can't be attached to a custom post type, but the page type can be attached to a custom post type with `post_type` in the `page_type` method.

I will update the documentation. Thanks!

**Comment by nlemoine** [comment]
Thanks for the prompt reply!
