### ISSUE TITLE
[admin columns] - Page type & post type

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#72]
I noticed that Papi adds a custom column to every post type, whether there's used in Papi or not:
https://github.com/wp-papi/papi/blob/master/src/includes/admin/class-papi-admin.php#L386

There no logic filtering on which post type the column should be added:
https://github.com/wp-papi/papi/blob/master/src/includes/admin/class-papi-admin.php#L243

Unlike the page type filter:
https://github.com/wp-papi/papi/blob/master/src/includes/admin/class-papi-admin.php#L300

The post type filtering may be done on the class instantiation before seting up any hooks? What do you think?

**Comment by frozzare** [comment]
Thanks for your issue. I was thinking of this earlier today when I was working with a CPT that don't have page types. So I can confirm that this is a bug.

I will fix this in the next version Papi that I'm planning to release during next week.

**Comment by nlemoine** [comment]
Thanks.
