### ISSUE TITLE
[bug] - _papi_page_type translated

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#73]
I'm french and while using papi for a recent project, I noticed the page type value called `Home` was translated to `Accueil`.

That's because papi is using translation function `esc_attr_e` to escape attributes: 
https://github.com/wp-papi/papi/blob/master/src/includes/admin/class-papi-admin.php#L166

The PR attached resolves this issue. I didn't check the whole code base for all translations functions (`__(), _e(), _n(), _x(), _ex(), _nx(), esc_attr__(), esc_attr_e(), esc_attr_x(), esc_html__(), esc_html_e(), esc_html_x(), _n_noop(), _nx_noop(), translate_nooped_plural()`) but they shouldn't be used as shortcuts to output raw values.

**Comment by frozzare** [comment]
Oh, that's interesting. Haven't checked the source code before for `esc_attr_e`. Thanks for your pull request. Will try to checked the whole code base after more bugs like this.
