### ISSUE TITLE
[bug] - Text property

### ISSUE THREAD

**Issue by nlemoine** [wp-papi/papi#79]
Hey, 

https://github.com/wp-papi/papi/blob/master/src/includes/properties/class-papi-property-text.php#L30

`sanitize_text_field` isn't the good method here to escape the textearea property, here's what it does (extracted from docblock): 
- check for invalid UTF-8,
- Convert single < characters to entity,
- strip all tags,
- remove line breaks, tabs and extra white space,
- strip octets

Line breaks shouldn't be removed from a textarea, `<` characters probably shouldn't be converted to entity too. 

As the method is only applied when `allow_html` is set to false, the method used should therefore only strip html tags.

What do you think?

**Comment by frozzare** [comment]
You´re right. I will fix this and release a patch version since 2.3.0 dosen't have any release date for now.

**Comment by frozzare** [comment]
https://github.com/wp-papi/papi/releases/tag/v2.2.1

**Comment by nlemoine** [comment]
Thanks!

**Comment by nlemoine** [comment]
Hi, 

The text field still contain the `santize_text_field`: https://github.com/wp-papi/papi/blob/v2.3.4/src/includes/properties/class-papi-property-text.php#L30

The fix seems to have disappeared in the meantime.

**Comment by frozzare** [comment]
Thanks. Will fix this in 2.3.5

**Comment by nlemoine** [comment]
Thanks!
