### ISSUE TITLE
Remove default page type from drop down

### ISSUE THREAD

**Issue by rasmusbe** [wp-papi/papi#81]
Remove default page type from drop down when the page type is not possible to use. Perhaps when filter `show_standard_page_type_{post_type}` is false or `only_page_type_{post_type}` is set. Or add a filter like `hide_standard_page_type_from_filter`

**Comment by frozzare** [comment]
I added a if statement that runs `papi/settings/show_standard_page_type_{$post_type}` filter before adds it to the dropdown. Think that is better then creating a new filter.

**Comment by frozzare** [comment]
After consideration with @rasmusbe I added a new filter.

```
add_filter( 'papi/settings/show_standard_page_type_in_filter_page', '__return_false' );
```
