### ISSUE TITLE
Page Type disappears when using parent post type

### ISSUE THREAD

**Issue by EkAndreas** [wp-papi/papi#82]
The page type is lost when saving a post to a parent that is not of the same page type.
I'm in a need to "attach" different posts with different page types to one another.

**Comment by frozzare** [comment]
I can't reproduce this with dev-master. You should read https://github.com/wp-papi/papi/blob/master/CONTRIBUTING.md#bugs and leave more info about the possible bug so it's easier to reproduce.

This is how I did:

1. Create a parent page of a page type.
2. Create a child page to the parent page type with a different page type.
3. Both parent page and child page has a page type.

<img width="890" alt="skarmklipp 2015-08-30 20 42 53" src="https://cloud.githubusercontent.com/assets/14610/9568867/bb33ad30-4f57-11e5-9c5a-17e9e5daecfd.png">

**Comment by EkAndreas** [comment]
I was afraid I did report this to quick without to much info to reproduce. 
Just closing this and I will come back with more background to reproduce the error.
My workaround right now is to save a hidden papi property and check if page type is changed and putting it back. I think the problem appears when using several parent nodes.
