### ISSUE TITLE
How to add localization to property Datetime

### ISSUE THREAD

**Issue by EkAndreas** [wp-papi/papi#83]
Would like Swedish localization on the picaday Datetime control and wonder how to access customization.

**Comment by frozzare** [comment]
1. Look at [Pikaday](https://github.com/dbushell/Pikaday#internationalization) documentation about localization.
2. Papi does nothing with the customization and will never have any support for it.

**Comment by EkAndreas** [comment]
Ok, it's not PikaDay customization I would like to get change but the localization :-)
Perhaps it would be great to be able to add moment.js as well?

**Comment by EkAndreas** [comment]
I did try to get a grip on the render property part but with no luck :-)

**Comment by frozzare** [comment]
I added i18n support for Pikaday and it will be in version 2.3.0 that will be released soon.

**Comment by EkAndreas** [comment]
Ok, thanks!

**Comment by frozzare** [comment]
And moment.js (https://github.com/wp-papi/papi/blob/master/src/assets/js/components/moment.js) is included in Papi already!

**Comment by EkAndreas** [comment]
So the $settings_json is somehow rendered to the control properties. Can't see where :-)

**Comment by frozzare** [comment]
See line 81 https://github.com/wp-papi/papi/blob/master/src/includes/properties/class-papi-property-datetime.php#L81

**Comment by frozzare** [comment]
I added support for all Pikaday settings even if Papi don't has documentation about it. See https://github.com/wp-papi/papi/commit/63c9502439638077a6cf7ef113a8c6cc4f2a5b04

For example `showMonthAfterYear` will work even if Papi don't have it in [get_default_settings](https://github.com/wp-papi/papi/blob/master/src/includes/properties/class-papi-property-datetime.php#L18).
