### ISSUE TITLE
Update Page Type suggestion

### ISSUE THREAD

**Issue by EkAndreas** [wp-papi/papi#87]
Today it is possible to get the page type via the function: 
```php
$page_type = papi_get_page_type_id( $post_id );
```

I would like a correspondent update function to a post like:
```php
papi_update_page_type_id( $post_id, $page_type );
```

Today I'm using this:
```php
update_post_meta( $post_id, PAPI_PAGE_TYPE_KEY, $page_type );
```

So there is no rush at all, just making the API clean and easy to use :-)

**Comment by frozzare** [comment]
I think `papi_set_page_type` is cleaner then `papi_update_page_type_id`.

**Comment by EkAndreas** [comment]
Yes, it's something you shouldn't do very often to a post.
