### ISSUE TITLE
Don't use strict type checking when marking selected items in a dropdown

### ISSUE THREAD

**Issue by richardsweeney** [wp-papi/papi#88]
In class Papi_Property_Dropdown on line 75 when setting an item as selected the use of '===' is, I think, unnecessary. It caused me quite a few headaches when a numerical value (a post ID for instance) was returned as a string when fetched from the post_meta table and thus was not marked as selected in the dropdown.

```php
'selected' => $value === $settings->selected ? 'selected' : null
```

Can I make a plea to change this to

```php
'selected' => $value == $settings->selected ? 'selected' : null
```

Say the word and I'll shoot you a pull request!

**Comment by frozzare** [comment]
Can you give a code example that you think isn't working the way it should?

**Comment by richardsweeney** [comment]
Sure thing!

This doesn't work: the value of the year retrieved from the database is a string, not an int.

```php
<?php

class Winner_Page_Type extends Papi_Page_Type {

	/**
	* The page type meta options.
	*
	* @return array
	*/

	public function page_type () {
		return [
			'name'        => __( 'Winner', 'nlg' ),
			'description' => __( 'A winner', 'nlg' ),
			'post_type'   => [ 'winner' ],
			'template'    => 'winner.php',
		];
	}


	/**
	 * Lazy way to generate an array of years.
	 */
	private function generate_years_for_dropdown() {
		$years = [];
		$start = date( 'Y', strtotime( '-10 years' ) );
		$now   = date( 'Y' );

		for ( $now; $now >= $start; $now-- ) {
			$years[] = $now;
		}

		return $years;
	}

    public function register() {
        $this->box( __( 'Additional information', 'nlg' ), [
            papi_property( [
                'type'  => 'text',
                'title' => __( 'Ingress text', 'nlg' ),
                'slug'  => 'ingress',
            ] ),
            papi_property( [
                'type'  => 'dropdown',
                'title' => __( 'Year awarded', 'nlg' ),
                'slug'  => 'year',
                'settings' => [
			        'items' => $this->generate_years_for_dropdown(),
                ],
            ] )
        ] );

    }

}
```

But if change the generate years method to return a string it works:

```php
	private function generate_years_for_dropdown() {
		$years = [];
		$start = date( 'Y', strtotime( '-10 years' ) );
		$now   = date( 'Y' );

		for ( $now; $now >= $start; $now-- ) {
			$years[] = (string) $now;
		}

		return $years;
	}
```

**Comment by frozzare** [comment]
The solution is not `==`, it's bad. The solution is to cast values, for example `'2013'` is numeric so it can be converted to `2013`.

Since 2.3.0 is not far away I will fix this to 2.3.0.

**Comment by richardsweeney** [comment]
Sound like a plan! Will you test with is_numeric()?

Really enjoying Papi by the way! Massive thanks for all your amazing work on the project, it's an absolute joy to work with.

**Comment by frozzare** [comment]
Yes and I will look for this problem in other properties and not only for dropdown and not only for numeric values.

**Comment by frozzare** [comment]
Can you test with `dev-master` branch? 

the first value from `generate_years_for_dropdown` is string and the rest is int.

**Comment by richardsweeney** [comment]
I tried changing my composer version to 'dev-master' but after 'composer update' I can't enable the plugin.

```
Fatal error: Class 'Frozzare\Tank\Container' not found in /srv/www/naringslivsgalan/content/plugins/papi/src/papi-loader.php on line 13
```

**Comment by frozzare** [comment]
Yeah, 2.3.0 requires to be installed with composer, so when using `dev-master` it should install the `tank` package. As you can read [here](https://github.com/wp-papi/papi#installation) and see [here](https://github.com/wp-papi/papi/blob/master/composer.json#L26).

I did this change since Papi should be installed with Composer since I don't release Papi as plugin on wp.org

So I think there is a problem with your composer or that you aren't loading `vendor/autoload.php` in your root. With this `composer.json` it installs `tank` package.

```json
{
  "name": "test",
  "type": "project",
  "minimum-stability": "dev",
  "prefer-stable": true,
  "repositories": [
	{
	  "type": "composer",
	  "url": "http://wpackagist.org"
	}
  ],
  "require": {
	"php": ">=5.4",
	"composer/installers": "~1.0.12",
	"johnpbloch/wordpress": "~4.2",
	"wp-papi/papi": "dev-master"
  },
  "extra": {
	"installer-paths": {
	  "web/app/mu-plugins/{$name}/": [
		"type:wordpress-muplugin"
	  ],
	  "web/app/plugins/{$name}/": [
		"type:wordpress-plugin"
	  ],
	  "web/app/themes/{$name}/": [
		"type:wordpress-theme"
	  ]
	},
	"wordpress-install-dir": "web/wp"
  }
}
```

**Comment by frozzare** [comment]
I will update the documentation about that you need to load `vendor/autoload.php` since 2.3.0.

**Comment by frozzare** [comment]
Will think about if this is the right move, maybe have a own container in Papi is the right.

**Comment by frozzare** [comment]
I decided to bring back the container class into Papi. So 2.3.0 will not have any dependency and will not require that Composers autoload is loaded.

**Comment by richardsweeney** [comment]
This is working for me now in dev-master, I'll close this now.

**Comment by frozzare** [comment]
:+1:
