### ISSUE TITLE
Remove "Add new page type" view automatic when only one page type exists

### ISSUE THREAD

**Issue by EkAndreas** [wp-papi/papi#89]
Suggestion!

If only one single Page Type is registered to the CPT then the "Add new page type" -dialog should be hidden.

![Add new page type](http://www.andreasek.se/app/uploads/2015/09/mandrill-page-type.png)

Eg, "mandrill" is a CPT and I've attached a Page Type "Mandrill" to it with fields AND used the filter papi/settings/show_standard_page_type_mandrill (= false) to hide the "Standard page". Now, when adding a new post I would like to "jump over" the single choice of the Mandrill Page Type for the user :-)

**Comment by EkAndreas** [comment]
This should be useful when replacing ACF with Papi.

**Comment by frozzare** [comment]
There are a filter for this [today](https://wp-papi.github.io/docs/#only-page-type-for-post-type), but yes this can be automatic and start to deprecate the filter in feature version.

**Comment by frozzare** [comment]
Changed the topic since it's was totally wrong.

**Comment by EkAndreas** [comment]
Ok, thanks!

**Comment by EkAndreas** [comment]
Yes, the filter papi/settings/only_page_type_{$post_type} works. Thanks!

**Comment by frozzare** [comment]
The meta key `standard_page_type` exists in 2.3.0 and will now hide the standard page type when a post type has one page type. So in 2.3.0 you don't need to use the filter when having one page type for one post type.
