### ISSUE TITLE
Multisite (with directories) custom papi AJAX url incorrect

### ISSUE THREAD

**Issue by richardsweeney** [wp-papi/papi#90]
In /src/includes/admin/class-papi-admin-ajax.php there is a custom AJAX endpoint defined. This doesn't work on multisite when using directories (not sub domains) as the URL defined in ```ajaxUrl``` is relative.

For example: If I create a site on the network that receives the URL https://cool.com/campaign/, wp-admin will be at https://cool.com/campaign/wp-admin/ but the path to ```papi.ajaxUrl``` will be https://cool.com/papi-ajax/ which gives a 404.

A potential solution (this is my working hack) would be to give the full URL (as WordPress does for it's own ajaxurl).

```php
public function ajax_url() {
	$url = esc_url( trailingslashit( get_bloginfo( 'url' ) ) . 'papi-ajax/' ); ?>
	<script type="text/javascript">
		var papi = papi || {};
		papi.ajaxUrl = '<?php echo $url ?>';
	</script>
	<?php
}
```

This is not dependant on multisite and will work regardless of URL scheme.

Also, typically in this situation I'd use wp_localize_script() for passing PHP variables to JS.

**Comment by frozzare** [comment]
Thanks. Will look into this.

Regarding `wp_localize_script` is not needen since Papi don't do any localize stuff with `papi-ajax` so this won't change.

**Comment by frozzare** [comment]
Can you test if `2.x` branch works with directories?

**Comment by richardsweeney** [comment]
Yes, 2.x fixes this issue for me.
