### ISSUE TITLE
How about adding an option for multi select?

### ISSUE THREAD

**Issue by mhensdal** [wp-papi/papi#92]

**Comment by frozzare** [comment]
Thanks for your proposal, will look into this

**Comment by frozzare** [comment]
I'm not sure if this is a good idea, multi select works fine with the native dropdown but with select2 it's messy. 

If you like to try how it's to work with multi select and select2 you can try it out here https://select2.github.io/examples.html

**Comment by frozzare** [comment]
I'm closing this since I don't have any plan to add multiselect to dropdown property. Feel free to create your own property :smile:
