### ISSUE TITLE
Default values not set in new posts

### ISSUE THREAD

**Issue by EkAndreas** [wp-papi/papi#95]
When saving new post with page type there is no default value set.

The error is reproduced with this plugin:
[https://github.com/EkAndreas/papi-menu](https://github.com/EkAndreas/papi-menu)

**Comment by EkAndreas** [comment]
So 'value' should be used instead of 'default'

**Comment by frozzare** [comment]
No. `default` should be used.

**Comment by EkAndreas** [comment]
In my case I'm using 0 as default value and perhaps it isn't the best value to test :-)

**Comment by EkAndreas** [comment]
Yes, 'default' works perfectly. I'm using test value 0 that is the problem here.

**Comment by frozzare** [comment]
Have fix this, `default` with `0` on number will work.

**Comment by EkAndreas** [comment]
Great! It works!
