### ISSUE TITLE
Field values cache never cleaned

### ISSUE THREAD

**Issue by entr** [wp-papi/papi#98]
I am using persistent object-cache dropin and WP is always serving a cached values for fields, in admin at least. I dig a bit into papi setters/getters and notice there are a bunch of `wp_cache_set` and `wp_cache_get` but no `wp_cache_delete` which I guess should be happening on every meta update. But wait a minute! Isn't meta already cache-ready? Looking at `wp-includes/meta.php` we could find cache functions all over the place. Not quite sure papi needs additional caching, at least not for the meta.

**Comment by frozzare** [comment]
Yeah you're right. Will remove the cache fields. Papi cache some more stuff where you can't call a delete cache function since you don't know when to do it, like reading from the file system. 



Med vänlig hälsning,Fredrik

**Comment by frozzare** [comment]
Did some thinking on the train home and removing the cache isn't a great solution since the value from the database isn't the value that is returned from `papi_get_field` as you may notice. Converting the value after you load the right property type from the page type file and the value from the database. So adding `wp_cache_delete` is a better solution then removing the cache.

**Comment by frozzare** [comment]
@entr Do you have time to test `2.x` to see if that solves your problem?

**Comment by entr** [comment]
@frozzare Thanks for the quick fix. Not tried yet, I will soon.

Not sure how substantial the benefit of caching is though. If you are doing a query that WP doesn't already cache (which is unlikely) chances are you're interacting with memory data only. If having hundred of fields the speed gain would be substantial at the cost of memory overhead I think.

**Comment by frozzare** [comment]
Why do the converting of values more then once? Better to load it from the cache then do all things over and over.

**Comment by frozzare** [comment]
I will release 2.3.5 since there are some other fixes that needs to be released. I have tested the cache locally and it works as it should with the new cache fixes.

**Comment by entr** [comment]
Sadly I still have an issue with the cache. Repeaters only I think, only there the values are not refreshed.

**Comment by frozzare** [comment]
Will look into this, can reproduce it.

**Comment by frozzare** [comment]
Fix for 2.4.2 that will be out on monday (hopefully). Did place the delete cache function in `papi_update_property_meta_value` to late so array properties was excluded.

**Comment by entr** [comment]
https://github.com/wp-papi/papi/commit/8409cfa0710908ff3d2fdbe1bc962d806f3f10a7 works nice.
